# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visualiser.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMinimumSize(QtCore.QSize(0, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.previousButton = QtWidgets.QPushButton(self.centralwidget)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout.addWidget(self.previousButton)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.iterationNumber = QtWidgets.QLabel(self.centralwidget)
        self.iterationNumber.setText("")
        self.iterationNumber.setObjectName("iterationNumber")
        self.gridLayout.addWidget(self.iterationNumber, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.regenRefNumber = QtWidgets.QLabel(self.centralwidget)
        self.regenRefNumber.setText("")
        self.regenRefNumber.setObjectName("regenRefNumber")
        self.gridLayout.addWidget(self.regenRefNumber, 3, 3, 1, 1)
        self.statesNumber = QtWidgets.QLabel(self.centralwidget)
        self.statesNumber.setText("")
        self.statesNumber.setObjectName("statesNumber")
        self.gridLayout.addWidget(self.statesNumber, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.regenTotalNumber = QtWidgets.QLabel(self.centralwidget)
        self.regenTotalNumber.setText("")
        self.regenTotalNumber.setObjectName("regenTotalNumber")
        self.gridLayout.addWidget(self.regenTotalNumber, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.regenRefTotalNumber = QtWidgets.QLabel(self.centralwidget)
        self.regenRefTotalNumber.setText("")
        self.regenRefTotalNumber.setObjectName("regenRefTotalNumber")
        self.gridLayout.addWidget(self.regenRefTotalNumber, 5, 3, 1, 1)
        self.regenNumber = QtWidgets.QLabel(self.centralwidget)
        self.regenNumber.setText("")
        self.regenNumber.setObjectName("regenNumber")
        self.gridLayout.addWidget(self.regenNumber, 2, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.playText = QtWidgets.QLabel(self.centralwidget)
        self.playText.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playText.setText("")
        self.playText.setAlignment(QtCore.Qt.AlignCenter)
        self.playText.setObjectName("playText")
        self.verticalLayout_3.addWidget(self.playText)
        self.gameLabel = QtWidgets.QLabel(self.centralwidget)
        self.gameLabel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.gameLabel.setText("")
        self.gameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.gameLabel.setObjectName("gameLabel")
        self.verticalLayout_3.addWidget(self.gameLabel)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.playEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.playEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.playEdit.setObjectName("playEdit")
        self.horizontalLayout_4.addWidget(self.playEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.playButton.setObjectName("playButton")
        self.verticalLayout_3.addWidget(self.playButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Limited memory MCTS visualiser"))
        self.previousButton.setText(_translate("MainWindow", "Previous iteration"))
        self.nextButton.setText(_translate("MainWindow", "Next iteration"))
        self.label_5.setText(_translate("MainWindow", "(Reference) States regenerated so far"))
        self.label.setText(_translate("MainWindow", "Iteration #"))
        self.label_3.setText(_translate("MainWindow", "States before optimisation"))
        self.label_6.setText(_translate("MainWindow", "(Reference) States regenerated this iteration"))
        self.label_2.setText(_translate("MainWindow", "States regenerated this iteration"))
        self.label_4.setText(_translate("MainWindow", "States regenerated so far"))
        self.label_7.setText(_translate("MainWindow", "0-8"))
        self.playButton.setText(_translate("MainWindow", "Play"))

